name: auto_nueip
description: "A new Flutter project."

publish_to: "none"
version: 1.1.4+6

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # network
  dio: ^5.9.0
  html: ^0.15.5+1
  cookie_jar: ^4.0.8
  webview_flutter: ^4.11.0
  pretty_dio_logger: ^1.4.0
  dio_cookie_manager: ^3.3.0
  cached_network_image: ^3.4.1

  # state
  joker_state: ^4.2.0+2

  # UI
  gap: ^3.0.1
  google_fonts: ^6.3.3
  toastification: ^3.0.3
  flutter_animate: ^4.5.2
  dropdown_button2: ^2.3.9
  salomon_bottom_bar: ^3.3.2
  flutter_screenutil: ^6.0.0-alpha.1
  animated_flip_counter: ^0.3.4
  syncfusion_flutter_calendar: ^31.2.16
  flutter_staggered_animations: ^1.1.1
  syncfusion_flutter_datepicker: ^31.2.16

  # Utils
  intl: ^0.20.2
  fpdart: ^1.2.0
  geolocator: ^13.0.2
  geocoding: ^4.0.0
  open_file: ^3.5.10
  photo_view: ^0.15.0
  collection: ^1.19.1
  auto_route: ^11.0.0
  file_picker: ^10.3.7
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  geofencing_api: ^2.0.0
  json_annotation: ^4.9.0
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.0+1
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.1.2
  flutter_form_builder: ^10.2.0
  flutter_foreground_task: ^9.1.0
  form_builder_validators: ^11.1.2
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_lints: ^6.0.0

  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icons/icon_android.png"
  adaptive_icon_foreground: "assets/icons/icon_android.png"
  adaptive_icon_monochrome: "assets/icons/icon_android.png"
  adaptive_icon_foreground_inset: 12
  adaptive_icon_background: "#ffffff"
  image_path_ios: "assets/icons/icon_ios.png"
  min_sdk_android: 34

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
